/* This code was generated by Usuba.
   See https://github.com/DadaIsCrazy/usuba.
   From the file "nist/photon-beetle/usuba/ua/photon_vslice.ua" (included below). */

#include <stdint.h>

/* Do NOT change the order of those define/include */

#ifndef BITS_PER_REG
#define BITS_PER_REG 4
#endif
/* including the architecture specific .h */
#include "STD.h"

/* auxiliary functions */
void Sbox__V4 (/*inputs*/ DATATYPE x__, /*outputs*/ DATATYPE* y__) {
   static const DATATYPE t[16] = { 12,5,6,11,9,0,10,13,3,14,15,8,4,7,1,2 };
   *y__ = t[x__];
}

/* main function */
void Photon__ (/*inputs*/ DATATYPE plain__[8][8], /*outputs*/ DATATYPE cipher__[8][8]) {

  // Variables declaration
  DATATYPE AddConstant__V4_1_IC__[8];
  DATATYPE AddConstant__V4_1__tmp9_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__1_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__2_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__3_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__4_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__5_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__6_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__7_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp15_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp16_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp17_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp18_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp19_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp20_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp21_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_1__tmp12_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_1__tmp13_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_1_c__;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_1_t__;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_2__tmp12_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_2__tmp13_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_2_c__;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_2_t__;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_3__tmp12_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_3__tmp13_;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_3_c__;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_3_t__;
  DATATYPE MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[8];
  DATATYPE RC__[12];
  DATATYPE _tmp35_[8][8];
  DATATYPE _tmp36_[8][8];
  DATATYPE _tmp37_[8][8];
  DATATYPE state__[8][8];

  // Instructions (body)
  RC__[0] = LIFT_4(1);
  RC__[1] = LIFT_4(3);
  RC__[2] = LIFT_4(7);
  RC__[3] = LIFT_4(14);
  RC__[4] = LIFT_4(13);
  RC__[5] = LIFT_4(11);
  RC__[6] = LIFT_4(6);
  RC__[7] = LIFT_4(12);
  RC__[8] = LIFT_4(9);
  RC__[9] = LIFT_4(2);
  RC__[10] = LIFT_4(5);
  RC__[11] = LIFT_4(10);
  state__[0][0] = plain__[0][0];
  state__[0][1] = plain__[0][1];
  state__[0][2] = plain__[0][2];
  state__[0][3] = plain__[0][3];
  state__[0][4] = plain__[0][4];
  state__[0][5] = plain__[0][5];
  state__[0][6] = plain__[0][6];
  state__[0][7] = plain__[0][7];
  state__[1][0] = plain__[1][0];
  state__[1][1] = plain__[1][1];
  state__[1][2] = plain__[1][2];
  state__[1][3] = plain__[1][3];
  state__[1][4] = plain__[1][4];
  state__[1][5] = plain__[1][5];
  state__[1][6] = plain__[1][6];
  state__[1][7] = plain__[1][7];
  state__[2][0] = plain__[2][0];
  state__[2][1] = plain__[2][1];
  state__[2][2] = plain__[2][2];
  state__[2][3] = plain__[2][3];
  state__[2][4] = plain__[2][4];
  state__[2][5] = plain__[2][5];
  state__[2][6] = plain__[2][6];
  state__[2][7] = plain__[2][7];
  state__[3][0] = plain__[3][0];
  state__[3][1] = plain__[3][1];
  state__[3][2] = plain__[3][2];
  state__[3][3] = plain__[3][3];
  state__[3][4] = plain__[3][4];
  state__[3][5] = plain__[3][5];
  state__[3][6] = plain__[3][6];
  state__[3][7] = plain__[3][7];
  state__[4][0] = plain__[4][0];
  state__[4][1] = plain__[4][1];
  state__[4][2] = plain__[4][2];
  state__[4][3] = plain__[4][3];
  state__[4][4] = plain__[4][4];
  state__[4][5] = plain__[4][5];
  state__[4][6] = plain__[4][6];
  state__[4][7] = plain__[4][7];
  state__[5][0] = plain__[5][0];
  state__[5][1] = plain__[5][1];
  state__[5][2] = plain__[5][2];
  state__[5][3] = plain__[5][3];
  state__[5][4] = plain__[5][4];
  state__[5][5] = plain__[5][5];
  state__[5][6] = plain__[5][6];
  state__[5][7] = plain__[5][7];
  state__[6][0] = plain__[6][0];
  state__[6][1] = plain__[6][1];
  state__[6][2] = plain__[6][2];
  state__[6][3] = plain__[6][3];
  state__[6][4] = plain__[6][4];
  state__[6][5] = plain__[6][5];
  state__[6][6] = plain__[6][6];
  state__[6][7] = plain__[6][7];
  state__[7][0] = plain__[7][0];
  state__[7][1] = plain__[7][1];
  state__[7][2] = plain__[7][2];
  state__[7][3] = plain__[7][3];
  state__[7][4] = plain__[7][4];
  state__[7][5] = plain__[7][5];
  state__[7][6] = plain__[7][6];
  state__[7][7] = plain__[7][7];
  for (int i__ = 0; i__ <= 11; i__++) {
    AddConstant__V4_1_IC__[0] = LIFT_4(0);
    AddConstant__V4_1_IC__[1] = RC__[0];
    AddConstant__V4_1_IC__[2] = RC__[1];
    AddConstant__V4_1_IC__[3] = RC__[2];
    AddConstant__V4_1_IC__[4] = LIFT_4(15);
    AddConstant__V4_1_IC__[5] = RC__[3];
    AddConstant__V4_1_IC__[6] = RC__[7];
    AddConstant__V4_1_IC__[7] = LIFT_4(8);
    for (int i__5 = 0; i__5 <= 7; i__5++) {
      AddConstant__V4_1__tmp9_ = XOR(state__[i__5][0],RC__[i__]);
      _tmp35_[i__5][0] = XOR(AddConstant__V4_1__tmp9_,AddConstant__V4_1_IC__[i__5]);
      _tmp35_[i__5][1] = state__[i__5][1];
      _tmp35_[i__5][2] = state__[i__5][2];
      _tmp35_[i__5][3] = state__[i__5][3];
      _tmp35_[i__5][4] = state__[i__5][4];
      _tmp35_[i__5][5] = state__[i__5][5];
      _tmp35_[i__5][6] = state__[i__5][6];
      _tmp35_[i__5][7] = state__[i__5][7];
    }
    for (int i__1 = 0; i__1 <= 7; i__1++) {
      for (int j__2 = 0; j__2 <= 7; j__2++) {
        Sbox__V4(_tmp35_[i__1][j__2],&_tmp36_[i__1][j__2]);
      }
    }
    for (int i__3 = 0; i__3 <= 7; i__3++) {
      for (int j__4 = 0; j__4 <= 7; j__4++) {
        _tmp37_[i__3][j__4] = _tmp36_[i__3][((j__4 + i__3) % 8)];
      }
    }
    for (int i__7 = 0; i__7 <= 7; i__7++) {
      MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[0] = _tmp37_[0][i__7];
      MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[1] = _tmp37_[1][i__7];
      MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[2] = _tmp37_[2][i__7];
      MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[3] = _tmp37_[3][i__7];
      MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[4] = _tmp37_[4][i__7];
      MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[5] = _tmp37_[5][i__7];
      MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[6] = _tmp37_[6][i__7];
      MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[7] = _tmp37_[7][i__7];
      for (int i__68 = 0; i__68 <= 7; i__68++) {
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__1_ = XOR(MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[3],MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[5]);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_1_t__ = L_SHIFT(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__1_,1,4);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_1_c__ = R_SHIFT(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__1_,3,4);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_1__tmp12_ = XOR(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_1_t__,MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_1_c__);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_1__tmp13_ = L_SHIFT(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_1_c__,1,4);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__2_ = XOR(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_1__tmp12_,MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_1__tmp13_);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp15_ = XOR(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__2_,MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[1]);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp16_ = XOR(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp15_,MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[6]);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__3_ = XOR(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp16_,MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[7]);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_2_t__ = L_SHIFT(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__3_,1,4);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_2_c__ = R_SHIFT(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__3_,3,4);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_2__tmp12_ = XOR(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_2_t__,MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_2_c__);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_2__tmp13_ = L_SHIFT(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_2_c__,1,4);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__4_ = XOR(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_2__tmp12_,MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_2__tmp13_);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp17_ = XOR(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__4_,MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[0]);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp18_ = XOR(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp17_,MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[2]);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp19_ = XOR(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp18_,MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[3]);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp20_ = XOR(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp19_,MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[4]);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__5_ = XOR(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp20_,MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[7]);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_3_t__ = L_SHIFT(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__5_,1,4);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_3_c__ = R_SHIFT(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__5_,3,4);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_3__tmp12_ = XOR(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_3_t__,MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_3_c__);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_3__tmp13_ = L_SHIFT(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_3_c__,1,4);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__6_ = XOR(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_3__tmp12_,MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1_xtimes__V4_3__tmp13_);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp21_ = XOR(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__6_,MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[3]);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__7_ = XOR(MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__tmp21_,MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[6]);
        MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[0] = MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[1];
        MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[1] = MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[2];
        MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[2] = MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[3];
        MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[3] = MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[4];
        MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[4] = MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[5];
        MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[5] = MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[6];
        MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[6] = MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[7];
        MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[7] = MixColumnSerial__V4_1_MixColumnRow__V4_1_step__V4_1__shadow_acc__7_;
      }
      state__[0][i__7] = MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[0];
      state__[1][i__7] = MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[1];
      state__[2][i__7] = MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[2];
      state__[3][i__7] = MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[3];
      state__[4][i__7] = MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[4];
      state__[5][i__7] = MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[5];
      state__[6][i__7] = MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[6];
      state__[7][i__7] = MixColumnSerial__V4_1_MixColumnRow__V4_1_x__[7];
    }
  }
  cipher__[0][0] = state__[0][0];
  cipher__[0][1] = state__[0][1];
  cipher__[0][2] = state__[0][2];
  cipher__[0][3] = state__[0][3];
  cipher__[0][4] = state__[0][4];
  cipher__[0][5] = state__[0][5];
  cipher__[0][6] = state__[0][6];
  cipher__[0][7] = state__[0][7];
  cipher__[1][0] = state__[1][0];
  cipher__[1][1] = state__[1][1];
  cipher__[1][2] = state__[1][2];
  cipher__[1][3] = state__[1][3];
  cipher__[1][4] = state__[1][4];
  cipher__[1][5] = state__[1][5];
  cipher__[1][6] = state__[1][6];
  cipher__[1][7] = state__[1][7];
  cipher__[2][0] = state__[2][0];
  cipher__[2][1] = state__[2][1];
  cipher__[2][2] = state__[2][2];
  cipher__[2][3] = state__[2][3];
  cipher__[2][4] = state__[2][4];
  cipher__[2][5] = state__[2][5];
  cipher__[2][6] = state__[2][6];
  cipher__[2][7] = state__[2][7];
  cipher__[3][0] = state__[3][0];
  cipher__[3][1] = state__[3][1];
  cipher__[3][2] = state__[3][2];
  cipher__[3][3] = state__[3][3];
  cipher__[3][4] = state__[3][4];
  cipher__[3][5] = state__[3][5];
  cipher__[3][6] = state__[3][6];
  cipher__[3][7] = state__[3][7];
  cipher__[4][0] = state__[4][0];
  cipher__[4][1] = state__[4][1];
  cipher__[4][2] = state__[4][2];
  cipher__[4][3] = state__[4][3];
  cipher__[4][4] = state__[4][4];
  cipher__[4][5] = state__[4][5];
  cipher__[4][6] = state__[4][6];
  cipher__[4][7] = state__[4][7];
  cipher__[5][0] = state__[5][0];
  cipher__[5][1] = state__[5][1];
  cipher__[5][2] = state__[5][2];
  cipher__[5][3] = state__[5][3];
  cipher__[5][4] = state__[5][4];
  cipher__[5][5] = state__[5][5];
  cipher__[5][6] = state__[5][6];
  cipher__[5][7] = state__[5][7];
  cipher__[6][0] = state__[6][0];
  cipher__[6][1] = state__[6][1];
  cipher__[6][2] = state__[6][2];
  cipher__[6][3] = state__[6][3];
  cipher__[6][4] = state__[6][4];
  cipher__[6][5] = state__[6][5];
  cipher__[6][6] = state__[6][6];
  cipher__[6][7] = state__[6][7];
  cipher__[7][0] = state__[7][0];
  cipher__[7][1] = state__[7][1];
  cipher__[7][2] = state__[7][2];
  cipher__[7][3] = state__[7][3];
  cipher__[7][4] = state__[7][4];
  cipher__[7][5] = state__[7][5];
  cipher__[7][6] = state__[7][6];
  cipher__[7][7] = state__[7][7];

}


/* **************************************************************** */
/*                            Usuba source                          */
/*                                                                  */
/*

 _no_inline table Sbox(x :  u4 :: base)
  returns y :  u4 :: base
{
  12, 5, 6, 11, 9, 0, 10, 13, 3, 14, 15, 8, 4, 7, 1, 2
}


 node SubCells(x :  u4[8][8] :: base)
  returns y :  u4[8][8] :: base
vars

let
  forall i in [0,7] {
    forall j in [0,7] {
      (y[i][j]) = Sbox(x[i][j])
    }
  }
tel

 node ShiftRows(x :  u4[8][8] :: base)
  returns y :  u4[8][8] :: base
vars

let
  forall i in [0,7] {
    forall j in [0,7] {
      (y[i][j]) = x[i][((j + i) % 8)]
    }
  }
tel

 node AddConstant(x :  u4[8][8] :: base,rc :  u4 :: base)
  returns y :  u4[8][8] :: base
vars
  IC :  u4[8] :: base
let
  (IC) = (0,1,3,7,15,14,12,8);
  forall i in [0,7] {
    (y[i][0]) = ((x[i][0] ^ rc) ^ IC[i]);
    (y[i][1 .. 7]) = x[i][1 .. 7]
  }
tel

 node xtimes(e :  u4 :: base)
  returns e' :  u4 :: base
vars
  t :  u4 :: base,
  c :  u4 :: base
let
  (t) = (e << 1);
  (c) = (e >> 3);
  (e') = (((t & 15) ^ c) ^ (c << 1))
tel

 node step(x :  u4[8] :: base)
  returns x' :  u4[8] :: base
vars
  acc :  u4 :: base
let
  (acc) = 0;
  (acc) := ((acc ^ x[3]) ^ x[5]);
  (acc) := xtimes(acc);
  (acc) := (((acc ^ x[1]) ^ x[6]) ^ x[7]);
  (acc) := xtimes(acc);
  (acc) := (((((acc ^ x[0]) ^ x[2]) ^ x[3]) ^ x[4]) ^ x[7]);
  (acc) := xtimes(acc);
  (acc) := ((acc ^ x[3]) ^ x[6]);
  (x') = (x[1 .. 7],acc)
tel

 node MixColumnRow(X :  u4[8] :: base)
  returns Y :  u4[8] :: base
vars
  x :  u4[9][8] :: base,
  y :  u4[9] :: base
let
  forall i in [0,7] {
    (x[0][i]) = (X[i] & 15)
  };
  forall i in [0,7] {
    (x[(i + 1)]) = step(x[i])
  };
  (Y) = x[8]
tel

 node MixColumnSerial(X :  u4[8][8] :: base)
  returns Y :  u4[8][8] :: base
vars

let
  forall i in [0,7] {
    (Y[0 .. 7][i]) = MixColumnRow(X[0 .. 7][i])
  }
tel

 node Photon(plain :  u4[8][8] :: base)
  returns cipher :  u4[8][8] :: base
vars
  RC :  u4[12] :: base,
  state :  u4[13][8][8] :: base
let
  (RC) = (1,3,7,14,13,11,6,12,9,2,5,10);
  (state[0]) = plain;
  forall i in [0,11] {
    (state[(i + 1)]) = MixColumnSerial(ShiftRows(SubCells(AddConstant(state[i],RC[i]))))
  };
  (cipher) = state[12]
tel

*/
 