#!/usr/bin/perl

=head1 Description

    This scripts checks that the code generated by Usuba for the
    ciphers DES (bitslice), AES (bitslice/hslice), Serpent (vslice)
    and Chacha20 (vslice) are correct.

    All the work is actually handed to the scripts of
    checks/correctness, but they all do similar things: they compile
    the Usuba source, link the resulting C file with a runtime, and
    compare the output they produce with a reference implementation
    (or a reference output in the case of Chacha20).

=cut

use strict;
use warnings;
use v5.14;

use Cwd;
use File::Path qw( remove_tree );
use File::Copy;
use FindBin;

sub error {
    say "************ ERROR **************";
    exit $?;
}

# switching to usuba dir
chdir $FindBin::Bin;

say "################################ Compiling ############################";
error if system 'make';
say "\n";


say "###################### Correctness verifications ######################\n";
system "./$_ 1" for glob('checks/correctness/*.pl');
