/* This code was generated by Usuba.
   See https://github.com/DadaIsCrazy/usuba.
   From the file "nist/photon-beetle/usuba/ua/photon_bitslice.ua" (included below). */

#include <stdint.h>

/* Do NOT change the order of those define/include */

#ifndef BITS_PER_REG
#define BITS_PER_REG 64
#endif
/* including the architecture specific .h */
#include "STD.h"

/* auxiliary functions */
void Sbox__B1 (/*inputs*/ DATATYPE X3,DATATYPE X2,DATATYPE X1,DATATYPE X0, /*outputs*/ DATATYPE* Y3,DATATYPE* Y2,DATATYPE* Y1,DATATYPE* Y0) {

  // Variables declaration
  DATATYPE T1;
  DATATYPE T2;
  DATATYPE T3;
  DATATYPE T4;
  DATATYPE T5;
  DATATYPE T6;
  DATATYPE T7;
  DATATYPE T8;
  DATATYPE T9;
  DATATYPE _tmp1_;

  // Instructions (body)
  T1 = XOR(X1,X2);
  T2 = AND(X2,T1);
  T3 = XOR(X3,T2);
  *Y0 = XOR(X0,T3);
  T4 = AND(T1,T3);
  T5 = XOR(T1,*Y0);
  T6 = XOR(T4,X2);
  T7 = OR(X0,T6);
  *Y1 = XOR(T5,T7);
  _tmp1_ = NOT(X0);
  T8 = XOR(T6,_tmp1_);
  *Y3 = XOR(*Y1,T8);
  T9 = OR(T8,T5);
  *Y2 = XOR(T3,T9);

}

/* main function */
void Photon__ (/*inputs*/ DATATYPE plain__[8][8][4], /*outputs*/ DATATYPE cipher__[8][8][4]) {

  // Variables declaration
  DATATYPE AddConstant__B1_1_IC__[8][4];
  DATATYPE AddConstant__B1_1__tmp10_[4];
  DATATYPE AddConstant__B1_1__tmp2_[4];
  DATATYPE AddConstant__B1_1__tmp3_[4];
  DATATYPE AddConstant__B1_1__tmp4_[4];
  DATATYPE AddConstant__B1_1__tmp5_[4];
  DATATYPE AddConstant__B1_1__tmp6_[4];
  DATATYPE AddConstant__B1_1__tmp7_[4];
  DATATYPE AddConstant__B1_1__tmp8_[4];
  DATATYPE AddConstant__B1_1__tmp9_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__1_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__2_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__3_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__4_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__5_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__6_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__7_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp15_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp16_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp17_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp18_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp19_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp20_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp21_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp22_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_acc__[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp11_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp12_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp13_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp14_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_c__[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_t__[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp11_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp12_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp13_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp14_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_c__[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_t__[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp11_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp12_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp13_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp14_[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_c__[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_t__[4];
  DATATYPE MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[9][8][4];
  DATATYPE RC__[12][4];
  DATATYPE _tmp36_[8][8][4];
  DATATYPE _tmp37_[8][8][4];
  DATATYPE _tmp38_[8][8][4];
  DATATYPE state__[13][8][8][4];

  // Instructions (body)
  RC__[0][0] = SET_ALL_ZERO();
  RC__[0][1] = RC__[0][0];
  RC__[0][2] = RC__[0][1];
  RC__[0][3] = SET_ALL_ONE();
  RC__[1][0] = RC__[0][2];
  RC__[1][1] = RC__[1][0];
  RC__[1][2] = RC__[0][3];
  RC__[1][3] = RC__[1][2];
  RC__[2][0] = RC__[1][1];
  RC__[2][1] = RC__[1][3];
  RC__[2][2] = RC__[2][1];
  RC__[2][3] = RC__[2][2];
  RC__[3][0] = RC__[2][2];
  RC__[3][1] = RC__[2][2];
  RC__[3][2] = RC__[2][2];
  RC__[3][3] = RC__[1][1];
  RC__[4][0] = RC__[2][2];
  RC__[4][1] = RC__[2][2];
  RC__[4][2] = RC__[1][1];
  RC__[4][3] = RC__[2][2];
  RC__[5][0] = RC__[2][2];
  RC__[5][1] = RC__[1][1];
  RC__[5][2] = RC__[2][2];
  RC__[5][3] = RC__[2][2];
  RC__[6][0] = RC__[1][1];
  RC__[6][1] = RC__[2][2];
  RC__[6][2] = RC__[2][2];
  RC__[6][3] = RC__[1][1];
  RC__[7][0] = RC__[2][2];
  RC__[7][1] = RC__[2][2];
  RC__[7][2] = RC__[1][1];
  RC__[7][3] = RC__[1][1];
  RC__[8][0] = RC__[2][2];
  RC__[8][1] = RC__[1][1];
  RC__[8][2] = RC__[1][1];
  RC__[8][3] = RC__[2][2];
  RC__[9][0] = RC__[1][1];
  RC__[9][1] = RC__[1][1];
  RC__[9][2] = RC__[2][2];
  RC__[9][3] = RC__[1][1];
  RC__[10][0] = RC__[1][1];
  RC__[10][1] = RC__[2][2];
  RC__[10][2] = RC__[1][1];
  RC__[10][3] = RC__[2][2];
  RC__[11][0] = RC__[2][2];
  RC__[11][1] = RC__[1][1];
  RC__[11][2] = RC__[2][2];
  RC__[11][3] = RC__[1][1];
  state__[0][0][0][0] = plain__[0][0][0];
  state__[0][0][0][1] = plain__[0][0][1];
  state__[0][0][0][2] = plain__[0][0][2];
  state__[0][0][0][3] = plain__[0][0][3];
  state__[0][0][1][0] = plain__[0][1][0];
  state__[0][0][1][1] = plain__[0][1][1];
  state__[0][0][1][2] = plain__[0][1][2];
  state__[0][0][1][3] = plain__[0][1][3];
  state__[0][0][2][0] = plain__[0][2][0];
  state__[0][0][2][1] = plain__[0][2][1];
  state__[0][0][2][2] = plain__[0][2][2];
  state__[0][0][2][3] = plain__[0][2][3];
  state__[0][0][3][0] = plain__[0][3][0];
  state__[0][0][3][1] = plain__[0][3][1];
  state__[0][0][3][2] = plain__[0][3][2];
  state__[0][0][3][3] = plain__[0][3][3];
  state__[0][0][4][0] = plain__[0][4][0];
  state__[0][0][4][1] = plain__[0][4][1];
  state__[0][0][4][2] = plain__[0][4][2];
  state__[0][0][4][3] = plain__[0][4][3];
  state__[0][0][5][0] = plain__[0][5][0];
  state__[0][0][5][1] = plain__[0][5][1];
  state__[0][0][5][2] = plain__[0][5][2];
  state__[0][0][5][3] = plain__[0][5][3];
  state__[0][0][6][0] = plain__[0][6][0];
  state__[0][0][6][1] = plain__[0][6][1];
  state__[0][0][6][2] = plain__[0][6][2];
  state__[0][0][6][3] = plain__[0][6][3];
  state__[0][0][7][0] = plain__[0][7][0];
  state__[0][0][7][1] = plain__[0][7][1];
  state__[0][0][7][2] = plain__[0][7][2];
  state__[0][0][7][3] = plain__[0][7][3];
  state__[0][1][0][0] = plain__[1][0][0];
  state__[0][1][0][1] = plain__[1][0][1];
  state__[0][1][0][2] = plain__[1][0][2];
  state__[0][1][0][3] = plain__[1][0][3];
  state__[0][1][1][0] = plain__[1][1][0];
  state__[0][1][1][1] = plain__[1][1][1];
  state__[0][1][1][2] = plain__[1][1][2];
  state__[0][1][1][3] = plain__[1][1][3];
  state__[0][1][2][0] = plain__[1][2][0];
  state__[0][1][2][1] = plain__[1][2][1];
  state__[0][1][2][2] = plain__[1][2][2];
  state__[0][1][2][3] = plain__[1][2][3];
  state__[0][1][3][0] = plain__[1][3][0];
  state__[0][1][3][1] = plain__[1][3][1];
  state__[0][1][3][2] = plain__[1][3][2];
  state__[0][1][3][3] = plain__[1][3][3];
  state__[0][1][4][0] = plain__[1][4][0];
  state__[0][1][4][1] = plain__[1][4][1];
  state__[0][1][4][2] = plain__[1][4][2];
  state__[0][1][4][3] = plain__[1][4][3];
  state__[0][1][5][0] = plain__[1][5][0];
  state__[0][1][5][1] = plain__[1][5][1];
  state__[0][1][5][2] = plain__[1][5][2];
  state__[0][1][5][3] = plain__[1][5][3];
  state__[0][1][6][0] = plain__[1][6][0];
  state__[0][1][6][1] = plain__[1][6][1];
  state__[0][1][6][2] = plain__[1][6][2];
  state__[0][1][6][3] = plain__[1][6][3];
  state__[0][1][7][0] = plain__[1][7][0];
  state__[0][1][7][1] = plain__[1][7][1];
  state__[0][1][7][2] = plain__[1][7][2];
  state__[0][1][7][3] = plain__[1][7][3];
  state__[0][2][0][0] = plain__[2][0][0];
  state__[0][2][0][1] = plain__[2][0][1];
  state__[0][2][0][2] = plain__[2][0][2];
  state__[0][2][0][3] = plain__[2][0][3];
  state__[0][2][1][0] = plain__[2][1][0];
  state__[0][2][1][1] = plain__[2][1][1];
  state__[0][2][1][2] = plain__[2][1][2];
  state__[0][2][1][3] = plain__[2][1][3];
  state__[0][2][2][0] = plain__[2][2][0];
  state__[0][2][2][1] = plain__[2][2][1];
  state__[0][2][2][2] = plain__[2][2][2];
  state__[0][2][2][3] = plain__[2][2][3];
  state__[0][2][3][0] = plain__[2][3][0];
  state__[0][2][3][1] = plain__[2][3][1];
  state__[0][2][3][2] = plain__[2][3][2];
  state__[0][2][3][3] = plain__[2][3][3];
  state__[0][2][4][0] = plain__[2][4][0];
  state__[0][2][4][1] = plain__[2][4][1];
  state__[0][2][4][2] = plain__[2][4][2];
  state__[0][2][4][3] = plain__[2][4][3];
  state__[0][2][5][0] = plain__[2][5][0];
  state__[0][2][5][1] = plain__[2][5][1];
  state__[0][2][5][2] = plain__[2][5][2];
  state__[0][2][5][3] = plain__[2][5][3];
  state__[0][2][6][0] = plain__[2][6][0];
  state__[0][2][6][1] = plain__[2][6][1];
  state__[0][2][6][2] = plain__[2][6][2];
  state__[0][2][6][3] = plain__[2][6][3];
  state__[0][2][7][0] = plain__[2][7][0];
  state__[0][2][7][1] = plain__[2][7][1];
  state__[0][2][7][2] = plain__[2][7][2];
  state__[0][2][7][3] = plain__[2][7][3];
  state__[0][3][0][0] = plain__[3][0][0];
  state__[0][3][0][1] = plain__[3][0][1];
  state__[0][3][0][2] = plain__[3][0][2];
  state__[0][3][0][3] = plain__[3][0][3];
  state__[0][3][1][0] = plain__[3][1][0];
  state__[0][3][1][1] = plain__[3][1][1];
  state__[0][3][1][2] = plain__[3][1][2];
  state__[0][3][1][3] = plain__[3][1][3];
  state__[0][3][2][0] = plain__[3][2][0];
  state__[0][3][2][1] = plain__[3][2][1];
  state__[0][3][2][2] = plain__[3][2][2];
  state__[0][3][2][3] = plain__[3][2][3];
  state__[0][3][3][0] = plain__[3][3][0];
  state__[0][3][3][1] = plain__[3][3][1];
  state__[0][3][3][2] = plain__[3][3][2];
  state__[0][3][3][3] = plain__[3][3][3];
  state__[0][3][4][0] = plain__[3][4][0];
  state__[0][3][4][1] = plain__[3][4][1];
  state__[0][3][4][2] = plain__[3][4][2];
  state__[0][3][4][3] = plain__[3][4][3];
  state__[0][3][5][0] = plain__[3][5][0];
  state__[0][3][5][1] = plain__[3][5][1];
  state__[0][3][5][2] = plain__[3][5][2];
  state__[0][3][5][3] = plain__[3][5][3];
  state__[0][3][6][0] = plain__[3][6][0];
  state__[0][3][6][1] = plain__[3][6][1];
  state__[0][3][6][2] = plain__[3][6][2];
  state__[0][3][6][3] = plain__[3][6][3];
  state__[0][3][7][0] = plain__[3][7][0];
  state__[0][3][7][1] = plain__[3][7][1];
  state__[0][3][7][2] = plain__[3][7][2];
  state__[0][3][7][3] = plain__[3][7][3];
  state__[0][4][0][0] = plain__[4][0][0];
  state__[0][4][0][1] = plain__[4][0][1];
  state__[0][4][0][2] = plain__[4][0][2];
  state__[0][4][0][3] = plain__[4][0][3];
  state__[0][4][1][0] = plain__[4][1][0];
  state__[0][4][1][1] = plain__[4][1][1];
  state__[0][4][1][2] = plain__[4][1][2];
  state__[0][4][1][3] = plain__[4][1][3];
  state__[0][4][2][0] = plain__[4][2][0];
  state__[0][4][2][1] = plain__[4][2][1];
  state__[0][4][2][2] = plain__[4][2][2];
  state__[0][4][2][3] = plain__[4][2][3];
  state__[0][4][3][0] = plain__[4][3][0];
  state__[0][4][3][1] = plain__[4][3][1];
  state__[0][4][3][2] = plain__[4][3][2];
  state__[0][4][3][3] = plain__[4][3][3];
  state__[0][4][4][0] = plain__[4][4][0];
  state__[0][4][4][1] = plain__[4][4][1];
  state__[0][4][4][2] = plain__[4][4][2];
  state__[0][4][4][3] = plain__[4][4][3];
  state__[0][4][5][0] = plain__[4][5][0];
  state__[0][4][5][1] = plain__[4][5][1];
  state__[0][4][5][2] = plain__[4][5][2];
  state__[0][4][5][3] = plain__[4][5][3];
  state__[0][4][6][0] = plain__[4][6][0];
  state__[0][4][6][1] = plain__[4][6][1];
  state__[0][4][6][2] = plain__[4][6][2];
  state__[0][4][6][3] = plain__[4][6][3];
  state__[0][4][7][0] = plain__[4][7][0];
  state__[0][4][7][1] = plain__[4][7][1];
  state__[0][4][7][2] = plain__[4][7][2];
  state__[0][4][7][3] = plain__[4][7][3];
  state__[0][5][0][0] = plain__[5][0][0];
  state__[0][5][0][1] = plain__[5][0][1];
  state__[0][5][0][2] = plain__[5][0][2];
  state__[0][5][0][3] = plain__[5][0][3];
  state__[0][5][1][0] = plain__[5][1][0];
  state__[0][5][1][1] = plain__[5][1][1];
  state__[0][5][1][2] = plain__[5][1][2];
  state__[0][5][1][3] = plain__[5][1][3];
  state__[0][5][2][0] = plain__[5][2][0];
  state__[0][5][2][1] = plain__[5][2][1];
  state__[0][5][2][2] = plain__[5][2][2];
  state__[0][5][2][3] = plain__[5][2][3];
  state__[0][5][3][0] = plain__[5][3][0];
  state__[0][5][3][1] = plain__[5][3][1];
  state__[0][5][3][2] = plain__[5][3][2];
  state__[0][5][3][3] = plain__[5][3][3];
  state__[0][5][4][0] = plain__[5][4][0];
  state__[0][5][4][1] = plain__[5][4][1];
  state__[0][5][4][2] = plain__[5][4][2];
  state__[0][5][4][3] = plain__[5][4][3];
  state__[0][5][5][0] = plain__[5][5][0];
  state__[0][5][5][1] = plain__[5][5][1];
  state__[0][5][5][2] = plain__[5][5][2];
  state__[0][5][5][3] = plain__[5][5][3];
  state__[0][5][6][0] = plain__[5][6][0];
  state__[0][5][6][1] = plain__[5][6][1];
  state__[0][5][6][2] = plain__[5][6][2];
  state__[0][5][6][3] = plain__[5][6][3];
  state__[0][5][7][0] = plain__[5][7][0];
  state__[0][5][7][1] = plain__[5][7][1];
  state__[0][5][7][2] = plain__[5][7][2];
  state__[0][5][7][3] = plain__[5][7][3];
  state__[0][6][0][0] = plain__[6][0][0];
  state__[0][6][0][1] = plain__[6][0][1];
  state__[0][6][0][2] = plain__[6][0][2];
  state__[0][6][0][3] = plain__[6][0][3];
  state__[0][6][1][0] = plain__[6][1][0];
  state__[0][6][1][1] = plain__[6][1][1];
  state__[0][6][1][2] = plain__[6][1][2];
  state__[0][6][1][3] = plain__[6][1][3];
  state__[0][6][2][0] = plain__[6][2][0];
  state__[0][6][2][1] = plain__[6][2][1];
  state__[0][6][2][2] = plain__[6][2][2];
  state__[0][6][2][3] = plain__[6][2][3];
  state__[0][6][3][0] = plain__[6][3][0];
  state__[0][6][3][1] = plain__[6][3][1];
  state__[0][6][3][2] = plain__[6][3][2];
  state__[0][6][3][3] = plain__[6][3][3];
  state__[0][6][4][0] = plain__[6][4][0];
  state__[0][6][4][1] = plain__[6][4][1];
  state__[0][6][4][2] = plain__[6][4][2];
  state__[0][6][4][3] = plain__[6][4][3];
  state__[0][6][5][0] = plain__[6][5][0];
  state__[0][6][5][1] = plain__[6][5][1];
  state__[0][6][5][2] = plain__[6][5][2];
  state__[0][6][5][3] = plain__[6][5][3];
  state__[0][6][6][0] = plain__[6][6][0];
  state__[0][6][6][1] = plain__[6][6][1];
  state__[0][6][6][2] = plain__[6][6][2];
  state__[0][6][6][3] = plain__[6][6][3];
  state__[0][6][7][0] = plain__[6][7][0];
  state__[0][6][7][1] = plain__[6][7][1];
  state__[0][6][7][2] = plain__[6][7][2];
  state__[0][6][7][3] = plain__[6][7][3];
  state__[0][7][0][0] = plain__[7][0][0];
  state__[0][7][0][1] = plain__[7][0][1];
  state__[0][7][0][2] = plain__[7][0][2];
  state__[0][7][0][3] = plain__[7][0][3];
  state__[0][7][1][0] = plain__[7][1][0];
  state__[0][7][1][1] = plain__[7][1][1];
  state__[0][7][1][2] = plain__[7][1][2];
  state__[0][7][1][3] = plain__[7][1][3];
  state__[0][7][2][0] = plain__[7][2][0];
  state__[0][7][2][1] = plain__[7][2][1];
  state__[0][7][2][2] = plain__[7][2][2];
  state__[0][7][2][3] = plain__[7][2][3];
  state__[0][7][3][0] = plain__[7][3][0];
  state__[0][7][3][1] = plain__[7][3][1];
  state__[0][7][3][2] = plain__[7][3][2];
  state__[0][7][3][3] = plain__[7][3][3];
  state__[0][7][4][0] = plain__[7][4][0];
  state__[0][7][4][1] = plain__[7][4][1];
  state__[0][7][4][2] = plain__[7][4][2];
  state__[0][7][4][3] = plain__[7][4][3];
  state__[0][7][5][0] = plain__[7][5][0];
  state__[0][7][5][1] = plain__[7][5][1];
  state__[0][7][5][2] = plain__[7][5][2];
  state__[0][7][5][3] = plain__[7][5][3];
  state__[0][7][6][0] = plain__[7][6][0];
  state__[0][7][6][1] = plain__[7][6][1];
  state__[0][7][6][2] = plain__[7][6][2];
  state__[0][7][6][3] = plain__[7][6][3];
  state__[0][7][7][0] = plain__[7][7][0];
  state__[0][7][7][1] = plain__[7][7][1];
  state__[0][7][7][2] = plain__[7][7][2];
  state__[0][7][7][3] = plain__[7][7][3];
  for (int i__ = 0; i__ <= 11; i__++) {
    AddConstant__B1_1__tmp2_[0] = RC__[1][1];
    AddConstant__B1_1__tmp2_[1] = RC__[1][1];
    AddConstant__B1_1__tmp2_[2] = RC__[1][1];
    AddConstant__B1_1__tmp2_[3] = RC__[1][1];
    AddConstant__B1_1__tmp3_[0] = RC__[1][1];
    AddConstant__B1_1__tmp3_[1] = RC__[1][1];
    AddConstant__B1_1__tmp3_[2] = RC__[1][1];
    AddConstant__B1_1__tmp3_[3] = RC__[2][2];
    AddConstant__B1_1__tmp4_[0] = RC__[1][1];
    AddConstant__B1_1__tmp4_[1] = RC__[1][1];
    AddConstant__B1_1__tmp4_[2] = RC__[2][2];
    AddConstant__B1_1__tmp4_[3] = RC__[2][2];
    AddConstant__B1_1__tmp5_[0] = RC__[1][1];
    AddConstant__B1_1__tmp5_[1] = RC__[2][2];
    AddConstant__B1_1__tmp5_[2] = RC__[2][2];
    AddConstant__B1_1__tmp5_[3] = RC__[2][2];
    AddConstant__B1_1__tmp6_[0] = RC__[2][2];
    AddConstant__B1_1__tmp6_[1] = RC__[2][2];
    AddConstant__B1_1__tmp6_[2] = RC__[2][2];
    AddConstant__B1_1__tmp6_[3] = RC__[2][2];
    AddConstant__B1_1__tmp7_[0] = RC__[2][2];
    AddConstant__B1_1__tmp7_[1] = RC__[2][2];
    AddConstant__B1_1__tmp7_[2] = RC__[2][2];
    AddConstant__B1_1__tmp7_[3] = RC__[1][1];
    AddConstant__B1_1__tmp8_[0] = RC__[2][2];
    AddConstant__B1_1__tmp8_[1] = RC__[2][2];
    AddConstant__B1_1__tmp8_[2] = RC__[1][1];
    AddConstant__B1_1__tmp8_[3] = RC__[1][1];
    AddConstant__B1_1__tmp9_[0] = RC__[2][2];
    AddConstant__B1_1__tmp9_[1] = RC__[1][1];
    AddConstant__B1_1__tmp9_[2] = RC__[1][1];
    AddConstant__B1_1__tmp9_[3] = RC__[1][1];
    AddConstant__B1_1_IC__[0][0] = AddConstant__B1_1__tmp2_[0];
    AddConstant__B1_1_IC__[0][1] = AddConstant__B1_1__tmp2_[1];
    AddConstant__B1_1_IC__[0][2] = AddConstant__B1_1__tmp2_[2];
    AddConstant__B1_1_IC__[0][3] = AddConstant__B1_1__tmp2_[3];
    AddConstant__B1_1_IC__[1][0] = AddConstant__B1_1__tmp3_[0];
    AddConstant__B1_1_IC__[1][1] = AddConstant__B1_1__tmp3_[1];
    AddConstant__B1_1_IC__[1][2] = AddConstant__B1_1__tmp3_[2];
    AddConstant__B1_1_IC__[1][3] = AddConstant__B1_1__tmp3_[3];
    AddConstant__B1_1_IC__[2][0] = AddConstant__B1_1__tmp4_[0];
    AddConstant__B1_1_IC__[2][1] = AddConstant__B1_1__tmp4_[1];
    AddConstant__B1_1_IC__[2][2] = AddConstant__B1_1__tmp4_[2];
    AddConstant__B1_1_IC__[2][3] = AddConstant__B1_1__tmp4_[3];
    AddConstant__B1_1_IC__[3][0] = AddConstant__B1_1__tmp5_[0];
    AddConstant__B1_1_IC__[3][1] = AddConstant__B1_1__tmp5_[1];
    AddConstant__B1_1_IC__[3][2] = AddConstant__B1_1__tmp5_[2];
    AddConstant__B1_1_IC__[3][3] = AddConstant__B1_1__tmp5_[3];
    AddConstant__B1_1_IC__[4][0] = AddConstant__B1_1__tmp6_[0];
    AddConstant__B1_1_IC__[4][1] = AddConstant__B1_1__tmp6_[1];
    AddConstant__B1_1_IC__[4][2] = AddConstant__B1_1__tmp6_[2];
    AddConstant__B1_1_IC__[4][3] = AddConstant__B1_1__tmp6_[3];
    AddConstant__B1_1_IC__[5][0] = AddConstant__B1_1__tmp7_[0];
    AddConstant__B1_1_IC__[5][1] = AddConstant__B1_1__tmp7_[1];
    AddConstant__B1_1_IC__[5][2] = AddConstant__B1_1__tmp7_[2];
    AddConstant__B1_1_IC__[5][3] = AddConstant__B1_1__tmp7_[3];
    AddConstant__B1_1_IC__[6][0] = AddConstant__B1_1__tmp8_[0];
    AddConstant__B1_1_IC__[6][1] = AddConstant__B1_1__tmp8_[1];
    AddConstant__B1_1_IC__[6][2] = AddConstant__B1_1__tmp8_[2];
    AddConstant__B1_1_IC__[6][3] = AddConstant__B1_1__tmp8_[3];
    AddConstant__B1_1_IC__[7][0] = AddConstant__B1_1__tmp9_[0];
    AddConstant__B1_1_IC__[7][1] = AddConstant__B1_1__tmp9_[1];
    AddConstant__B1_1_IC__[7][2] = AddConstant__B1_1__tmp9_[2];
    AddConstant__B1_1_IC__[7][3] = AddConstant__B1_1__tmp9_[3];
    for (int i__5 = 0; i__5 <= 7; i__5++) {
      AddConstant__B1_1__tmp10_[0] = XOR(state__[i__][i__5][0][0],RC__[i__][0]);
      AddConstant__B1_1__tmp10_[1] = XOR(state__[i__][i__5][0][1],RC__[i__][1]);
      AddConstant__B1_1__tmp10_[2] = XOR(state__[i__][i__5][0][2],RC__[i__][2]);
      AddConstant__B1_1__tmp10_[3] = XOR(state__[i__][i__5][0][3],RC__[i__][3]);
      _tmp36_[i__5][0][0] = XOR(AddConstant__B1_1__tmp10_[0],AddConstant__B1_1_IC__[i__5][0]);
      _tmp36_[i__5][0][1] = XOR(AddConstant__B1_1__tmp10_[1],AddConstant__B1_1_IC__[i__5][1]);
      _tmp36_[i__5][0][2] = XOR(AddConstant__B1_1__tmp10_[2],AddConstant__B1_1_IC__[i__5][2]);
      _tmp36_[i__5][0][3] = XOR(AddConstant__B1_1__tmp10_[3],AddConstant__B1_1_IC__[i__5][3]);
      _tmp36_[i__5][1][0] = state__[i__][i__5][1][0];
      _tmp36_[i__5][1][1] = state__[i__][i__5][1][1];
      _tmp36_[i__5][1][2] = state__[i__][i__5][1][2];
      _tmp36_[i__5][1][3] = state__[i__][i__5][1][3];
      _tmp36_[i__5][2][0] = state__[i__][i__5][2][0];
      _tmp36_[i__5][2][1] = state__[i__][i__5][2][1];
      _tmp36_[i__5][2][2] = state__[i__][i__5][2][2];
      _tmp36_[i__5][2][3] = state__[i__][i__5][2][3];
      _tmp36_[i__5][3][0] = state__[i__][i__5][3][0];
      _tmp36_[i__5][3][1] = state__[i__][i__5][3][1];
      _tmp36_[i__5][3][2] = state__[i__][i__5][3][2];
      _tmp36_[i__5][3][3] = state__[i__][i__5][3][3];
      _tmp36_[i__5][4][0] = state__[i__][i__5][4][0];
      _tmp36_[i__5][4][1] = state__[i__][i__5][4][1];
      _tmp36_[i__5][4][2] = state__[i__][i__5][4][2];
      _tmp36_[i__5][4][3] = state__[i__][i__5][4][3];
      _tmp36_[i__5][5][0] = state__[i__][i__5][5][0];
      _tmp36_[i__5][5][1] = state__[i__][i__5][5][1];
      _tmp36_[i__5][5][2] = state__[i__][i__5][5][2];
      _tmp36_[i__5][5][3] = state__[i__][i__5][5][3];
      _tmp36_[i__5][6][0] = state__[i__][i__5][6][0];
      _tmp36_[i__5][6][1] = state__[i__][i__5][6][1];
      _tmp36_[i__5][6][2] = state__[i__][i__5][6][2];
      _tmp36_[i__5][6][3] = state__[i__][i__5][6][3];
      _tmp36_[i__5][7][0] = state__[i__][i__5][7][0];
      _tmp36_[i__5][7][1] = state__[i__][i__5][7][1];
      _tmp36_[i__5][7][2] = state__[i__][i__5][7][2];
      _tmp36_[i__5][7][3] = state__[i__][i__5][7][3];
    }
    for (int i__1 = 0; i__1 <= 7; i__1++) {
      for (int j__2 = 0; j__2 <= 7; j__2++) {
        Sbox__B1(_tmp36_[i__1][j__2][0],_tmp36_[i__1][j__2][1],_tmp36_[i__1][j__2][2],_tmp36_[i__1][j__2][3],&_tmp37_[i__1][j__2][0],&_tmp37_[i__1][j__2][1],&_tmp37_[i__1][j__2][2],&_tmp37_[i__1][j__2][3]);
      }
    }
    for (int i__3 = 0; i__3 <= 7; i__3++) {
      for (int j__4 = 0; j__4 <= 7; j__4++) {
        _tmp38_[i__3][j__4][0] = _tmp37_[i__3][((j__4 + i__3) % 8)][0];
        _tmp38_[i__3][j__4][1] = _tmp37_[i__3][((j__4 + i__3) % 8)][1];
        _tmp38_[i__3][j__4][2] = _tmp37_[i__3][((j__4 + i__3) % 8)][2];
        _tmp38_[i__3][j__4][3] = _tmp37_[i__3][((j__4 + i__3) % 8)][3];
      }
    }
    for (int i__7 = 0; i__7 <= 7; i__7++) {
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[0] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[1] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[2] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[3] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][0][0] = AND(_tmp38_[0][i__7][0],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[0]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][0][1] = AND(_tmp38_[0][i__7][1],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[1]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][0][2] = AND(_tmp38_[0][i__7][2],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[2]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][0][3] = AND(_tmp38_[0][i__7][3],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[3]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[0] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[1] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[2] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[3] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][1][0] = AND(_tmp38_[1][i__7][0],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[0]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][1][1] = AND(_tmp38_[1][i__7][1],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[1]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][1][2] = AND(_tmp38_[1][i__7][2],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[2]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][1][3] = AND(_tmp38_[1][i__7][3],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[3]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[0] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[1] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[2] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[3] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][2][0] = AND(_tmp38_[2][i__7][0],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[0]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][2][1] = AND(_tmp38_[2][i__7][1],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[1]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][2][2] = AND(_tmp38_[2][i__7][2],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[2]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][2][3] = AND(_tmp38_[2][i__7][3],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[3]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[0] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[1] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[2] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[3] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][3][0] = AND(_tmp38_[3][i__7][0],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[0]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][3][1] = AND(_tmp38_[3][i__7][1],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[1]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][3][2] = AND(_tmp38_[3][i__7][2],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[2]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][3][3] = AND(_tmp38_[3][i__7][3],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[3]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[0] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[1] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[2] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[3] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][4][0] = AND(_tmp38_[4][i__7][0],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[0]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][4][1] = AND(_tmp38_[4][i__7][1],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[1]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][4][2] = AND(_tmp38_[4][i__7][2],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[2]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][4][3] = AND(_tmp38_[4][i__7][3],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[3]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[0] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[1] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[2] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[3] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][5][0] = AND(_tmp38_[5][i__7][0],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[0]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][5][1] = AND(_tmp38_[5][i__7][1],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[1]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][5][2] = AND(_tmp38_[5][i__7][2],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[2]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][5][3] = AND(_tmp38_[5][i__7][3],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[3]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[0] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[1] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[2] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[3] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][6][0] = AND(_tmp38_[6][i__7][0],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[0]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][6][1] = AND(_tmp38_[6][i__7][1],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[1]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][6][2] = AND(_tmp38_[6][i__7][2],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[2]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][6][3] = AND(_tmp38_[6][i__7][3],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[3]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[0] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[1] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[2] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[3] = RC__[2][2];
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][7][0] = AND(_tmp38_[7][i__7][0],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[0]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][7][1] = AND(_tmp38_[7][i__7][1],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[1]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][7][2] = AND(_tmp38_[7][i__7][2],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[2]);
      MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[0][7][3] = AND(_tmp38_[7][i__7][3],MixColumnSerial__B1_1_MixColumnRow__B1_1__tmp23_[3]);
      for (int i__68 = 0; i__68 <= 7; i__68++) {
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_acc__[0] = RC__[1][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_acc__[1] = RC__[1][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_acc__[2] = RC__[1][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_acc__[3] = RC__[1][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp15_[0] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_acc__[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][3][0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp15_[1] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_acc__[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][3][1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp15_[2] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_acc__[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][3][2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp15_[3] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_acc__[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][3][3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__1_[0] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp15_[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][5][0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__1_[1] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp15_[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][5][1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__1_[2] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp15_[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][5][2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__1_[3] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp15_[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][5][3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_t__[0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__1_[1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_t__[1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__1_[2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_t__[2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__1_[3];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_t__[3] = RC__[1][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_c__[0] = RC__[1][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_c__[1] = RC__[1][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_c__[2] = RC__[1][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_c__[3] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__1_[0];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp11_[0] = RC__[2][2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp11_[1] = RC__[2][2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp11_[2] = RC__[2][2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp11_[3] = RC__[2][2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp12_[0] = AND(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_t__[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp11_[0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp12_[1] = AND(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_t__[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp11_[1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp12_[2] = AND(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_t__[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp11_[2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp12_[3] = AND(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_t__[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp11_[3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp13_[0] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp12_[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_c__[0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp13_[1] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp12_[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_c__[1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp13_[2] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp12_[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_c__[2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp13_[3] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp12_[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_c__[3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp14_[0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_c__[1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp14_[1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_c__[2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp14_[2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1_c__[3];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp14_[3] = RC__[1][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__2_[0] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp13_[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp14_[0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__2_[1] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp13_[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp14_[1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__2_[2] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp13_[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp14_[2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__2_[3] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp13_[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_1__tmp14_[3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp16_[0] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__2_[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][1][0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp16_[1] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__2_[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][1][1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp16_[2] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__2_[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][1][2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp16_[3] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__2_[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][1][3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp17_[0] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp16_[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][6][0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp17_[1] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp16_[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][6][1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp17_[2] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp16_[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][6][2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp17_[3] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp16_[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][6][3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__3_[0] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp17_[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][7][0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__3_[1] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp17_[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][7][1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__3_[2] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp17_[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][7][2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__3_[3] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp17_[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][7][3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_t__[0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__3_[1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_t__[1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__3_[2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_t__[2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__3_[3];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_t__[3] = RC__[1][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_c__[0] = RC__[1][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_c__[1] = RC__[1][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_c__[2] = RC__[1][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_c__[3] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__3_[0];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp11_[0] = RC__[2][2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp11_[1] = RC__[2][2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp11_[2] = RC__[2][2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp11_[3] = RC__[2][2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp12_[0] = AND(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_t__[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp11_[0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp12_[1] = AND(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_t__[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp11_[1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp12_[2] = AND(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_t__[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp11_[2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp12_[3] = AND(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_t__[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp11_[3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp13_[0] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp12_[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_c__[0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp13_[1] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp12_[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_c__[1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp13_[2] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp12_[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_c__[2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp13_[3] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp12_[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_c__[3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp14_[0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_c__[1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp14_[1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_c__[2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp14_[2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2_c__[3];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp14_[3] = RC__[1][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__4_[0] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp13_[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp14_[0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__4_[1] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp13_[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp14_[1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__4_[2] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp13_[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp14_[2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__4_[3] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp13_[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_2__tmp14_[3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp18_[0] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__4_[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][0][0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp18_[1] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__4_[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][0][1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp18_[2] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__4_[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][0][2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp18_[3] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__4_[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][0][3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp19_[0] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp18_[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][2][0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp19_[1] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp18_[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][2][1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp19_[2] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp18_[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][2][2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp19_[3] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp18_[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][2][3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp20_[0] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp19_[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][3][0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp20_[1] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp19_[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][3][1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp20_[2] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp19_[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][3][2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp20_[3] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp19_[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][3][3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp21_[0] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp20_[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][4][0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp21_[1] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp20_[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][4][1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp21_[2] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp20_[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][4][2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp21_[3] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp20_[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][4][3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__5_[0] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp21_[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][7][0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__5_[1] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp21_[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][7][1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__5_[2] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp21_[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][7][2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__5_[3] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp21_[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][7][3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_t__[0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__5_[1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_t__[1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__5_[2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_t__[2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__5_[3];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_t__[3] = RC__[1][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_c__[0] = RC__[1][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_c__[1] = RC__[1][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_c__[2] = RC__[1][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_c__[3] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__5_[0];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp11_[0] = RC__[2][2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp11_[1] = RC__[2][2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp11_[2] = RC__[2][2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp11_[3] = RC__[2][2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp12_[0] = AND(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_t__[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp11_[0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp12_[1] = AND(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_t__[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp11_[1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp12_[2] = AND(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_t__[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp11_[2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp12_[3] = AND(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_t__[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp11_[3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp13_[0] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp12_[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_c__[0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp13_[1] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp12_[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_c__[1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp13_[2] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp12_[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_c__[2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp13_[3] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp12_[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_c__[3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp14_[0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_c__[1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp14_[1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_c__[2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp14_[2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3_c__[3];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp14_[3] = RC__[1][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__6_[0] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp13_[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp14_[0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__6_[1] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp13_[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp14_[1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__6_[2] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp13_[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp14_[2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__6_[3] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp13_[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1_xtimes__B1_3__tmp14_[3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp22_[0] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__6_[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][3][0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp22_[1] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__6_[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][3][1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp22_[2] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__6_[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][3][2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp22_[3] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__6_[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][3][3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__7_[0] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp22_[0],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][6][0]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__7_[1] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp22_[1],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][6][1]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__7_[2] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp22_[2],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][6][2]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__7_[3] = XOR(MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__tmp22_[3],MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][6][3]);
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][0][0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][1][0];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][0][1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][1][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][0][2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][1][2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][0][3] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][1][3];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][1][0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][2][0];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][1][1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][2][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][1][2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][2][2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][1][3] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][2][3];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][2][0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][3][0];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][2][1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][3][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][2][2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][3][2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][2][3] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][3][3];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][3][0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][4][0];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][3][1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][4][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][3][2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][4][2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][3][3] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][4][3];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][4][0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][5][0];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][4][1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][5][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][4][2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][5][2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][4][3] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][5][3];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][5][0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][6][0];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][5][1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][6][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][5][2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][6][2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][5][3] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][6][3];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][6][0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][7][0];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][6][1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][7][1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][6][2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][7][2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][6][3] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[i__68][7][3];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][7][0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__7_[0];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][7][1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__7_[1];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][7][2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__7_[2];
        MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[(i__68 + 1)][7][3] = MixColumnSerial__B1_1_MixColumnRow__B1_1_step__B1_1__shadow_acc__7_[3];
      }
      state__[(i__ + 1)][0][i__7][0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][0][0];
      state__[(i__ + 1)][0][i__7][1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][0][1];
      state__[(i__ + 1)][0][i__7][2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][0][2];
      state__[(i__ + 1)][0][i__7][3] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][0][3];
      state__[(i__ + 1)][1][i__7][0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][1][0];
      state__[(i__ + 1)][1][i__7][1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][1][1];
      state__[(i__ + 1)][1][i__7][2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][1][2];
      state__[(i__ + 1)][1][i__7][3] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][1][3];
      state__[(i__ + 1)][2][i__7][0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][2][0];
      state__[(i__ + 1)][2][i__7][1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][2][1];
      state__[(i__ + 1)][2][i__7][2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][2][2];
      state__[(i__ + 1)][2][i__7][3] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][2][3];
      state__[(i__ + 1)][3][i__7][0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][3][0];
      state__[(i__ + 1)][3][i__7][1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][3][1];
      state__[(i__ + 1)][3][i__7][2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][3][2];
      state__[(i__ + 1)][3][i__7][3] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][3][3];
      state__[(i__ + 1)][4][i__7][0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][4][0];
      state__[(i__ + 1)][4][i__7][1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][4][1];
      state__[(i__ + 1)][4][i__7][2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][4][2];
      state__[(i__ + 1)][4][i__7][3] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][4][3];
      state__[(i__ + 1)][5][i__7][0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][5][0];
      state__[(i__ + 1)][5][i__7][1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][5][1];
      state__[(i__ + 1)][5][i__7][2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][5][2];
      state__[(i__ + 1)][5][i__7][3] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][5][3];
      state__[(i__ + 1)][6][i__7][0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][6][0];
      state__[(i__ + 1)][6][i__7][1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][6][1];
      state__[(i__ + 1)][6][i__7][2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][6][2];
      state__[(i__ + 1)][6][i__7][3] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][6][3];
      state__[(i__ + 1)][7][i__7][0] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][7][0];
      state__[(i__ + 1)][7][i__7][1] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][7][1];
      state__[(i__ + 1)][7][i__7][2] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][7][2];
      state__[(i__ + 1)][7][i__7][3] = MixColumnSerial__B1_1_MixColumnRow__B1_1_x__[8][7][3];
    }
  }
  cipher__[0][0][0] = state__[12][0][0][0];
  cipher__[0][0][1] = state__[12][0][0][1];
  cipher__[0][0][2] = state__[12][0][0][2];
  cipher__[0][0][3] = state__[12][0][0][3];
  cipher__[0][1][0] = state__[12][0][1][0];
  cipher__[0][1][1] = state__[12][0][1][1];
  cipher__[0][1][2] = state__[12][0][1][2];
  cipher__[0][1][3] = state__[12][0][1][3];
  cipher__[0][2][0] = state__[12][0][2][0];
  cipher__[0][2][1] = state__[12][0][2][1];
  cipher__[0][2][2] = state__[12][0][2][2];
  cipher__[0][2][3] = state__[12][0][2][3];
  cipher__[0][3][0] = state__[12][0][3][0];
  cipher__[0][3][1] = state__[12][0][3][1];
  cipher__[0][3][2] = state__[12][0][3][2];
  cipher__[0][3][3] = state__[12][0][3][3];
  cipher__[0][4][0] = state__[12][0][4][0];
  cipher__[0][4][1] = state__[12][0][4][1];
  cipher__[0][4][2] = state__[12][0][4][2];
  cipher__[0][4][3] = state__[12][0][4][3];
  cipher__[0][5][0] = state__[12][0][5][0];
  cipher__[0][5][1] = state__[12][0][5][1];
  cipher__[0][5][2] = state__[12][0][5][2];
  cipher__[0][5][3] = state__[12][0][5][3];
  cipher__[0][6][0] = state__[12][0][6][0];
  cipher__[0][6][1] = state__[12][0][6][1];
  cipher__[0][6][2] = state__[12][0][6][2];
  cipher__[0][6][3] = state__[12][0][6][3];
  cipher__[0][7][0] = state__[12][0][7][0];
  cipher__[0][7][1] = state__[12][0][7][1];
  cipher__[0][7][2] = state__[12][0][7][2];
  cipher__[0][7][3] = state__[12][0][7][3];
  cipher__[1][0][0] = state__[12][1][0][0];
  cipher__[1][0][1] = state__[12][1][0][1];
  cipher__[1][0][2] = state__[12][1][0][2];
  cipher__[1][0][3] = state__[12][1][0][3];
  cipher__[1][1][0] = state__[12][1][1][0];
  cipher__[1][1][1] = state__[12][1][1][1];
  cipher__[1][1][2] = state__[12][1][1][2];
  cipher__[1][1][3] = state__[12][1][1][3];
  cipher__[1][2][0] = state__[12][1][2][0];
  cipher__[1][2][1] = state__[12][1][2][1];
  cipher__[1][2][2] = state__[12][1][2][2];
  cipher__[1][2][3] = state__[12][1][2][3];
  cipher__[1][3][0] = state__[12][1][3][0];
  cipher__[1][3][1] = state__[12][1][3][1];
  cipher__[1][3][2] = state__[12][1][3][2];
  cipher__[1][3][3] = state__[12][1][3][3];
  cipher__[1][4][0] = state__[12][1][4][0];
  cipher__[1][4][1] = state__[12][1][4][1];
  cipher__[1][4][2] = state__[12][1][4][2];
  cipher__[1][4][3] = state__[12][1][4][3];
  cipher__[1][5][0] = state__[12][1][5][0];
  cipher__[1][5][1] = state__[12][1][5][1];
  cipher__[1][5][2] = state__[12][1][5][2];
  cipher__[1][5][3] = state__[12][1][5][3];
  cipher__[1][6][0] = state__[12][1][6][0];
  cipher__[1][6][1] = state__[12][1][6][1];
  cipher__[1][6][2] = state__[12][1][6][2];
  cipher__[1][6][3] = state__[12][1][6][3];
  cipher__[1][7][0] = state__[12][1][7][0];
  cipher__[1][7][1] = state__[12][1][7][1];
  cipher__[1][7][2] = state__[12][1][7][2];
  cipher__[1][7][3] = state__[12][1][7][3];
  cipher__[2][0][0] = state__[12][2][0][0];
  cipher__[2][0][1] = state__[12][2][0][1];
  cipher__[2][0][2] = state__[12][2][0][2];
  cipher__[2][0][3] = state__[12][2][0][3];
  cipher__[2][1][0] = state__[12][2][1][0];
  cipher__[2][1][1] = state__[12][2][1][1];
  cipher__[2][1][2] = state__[12][2][1][2];
  cipher__[2][1][3] = state__[12][2][1][3];
  cipher__[2][2][0] = state__[12][2][2][0];
  cipher__[2][2][1] = state__[12][2][2][1];
  cipher__[2][2][2] = state__[12][2][2][2];
  cipher__[2][2][3] = state__[12][2][2][3];
  cipher__[2][3][0] = state__[12][2][3][0];
  cipher__[2][3][1] = state__[12][2][3][1];
  cipher__[2][3][2] = state__[12][2][3][2];
  cipher__[2][3][3] = state__[12][2][3][3];
  cipher__[2][4][0] = state__[12][2][4][0];
  cipher__[2][4][1] = state__[12][2][4][1];
  cipher__[2][4][2] = state__[12][2][4][2];
  cipher__[2][4][3] = state__[12][2][4][3];
  cipher__[2][5][0] = state__[12][2][5][0];
  cipher__[2][5][1] = state__[12][2][5][1];
  cipher__[2][5][2] = state__[12][2][5][2];
  cipher__[2][5][3] = state__[12][2][5][3];
  cipher__[2][6][0] = state__[12][2][6][0];
  cipher__[2][6][1] = state__[12][2][6][1];
  cipher__[2][6][2] = state__[12][2][6][2];
  cipher__[2][6][3] = state__[12][2][6][3];
  cipher__[2][7][0] = state__[12][2][7][0];
  cipher__[2][7][1] = state__[12][2][7][1];
  cipher__[2][7][2] = state__[12][2][7][2];
  cipher__[2][7][3] = state__[12][2][7][3];
  cipher__[3][0][0] = state__[12][3][0][0];
  cipher__[3][0][1] = state__[12][3][0][1];
  cipher__[3][0][2] = state__[12][3][0][2];
  cipher__[3][0][3] = state__[12][3][0][3];
  cipher__[3][1][0] = state__[12][3][1][0];
  cipher__[3][1][1] = state__[12][3][1][1];
  cipher__[3][1][2] = state__[12][3][1][2];
  cipher__[3][1][3] = state__[12][3][1][3];
  cipher__[3][2][0] = state__[12][3][2][0];
  cipher__[3][2][1] = state__[12][3][2][1];
  cipher__[3][2][2] = state__[12][3][2][2];
  cipher__[3][2][3] = state__[12][3][2][3];
  cipher__[3][3][0] = state__[12][3][3][0];
  cipher__[3][3][1] = state__[12][3][3][1];
  cipher__[3][3][2] = state__[12][3][3][2];
  cipher__[3][3][3] = state__[12][3][3][3];
  cipher__[3][4][0] = state__[12][3][4][0];
  cipher__[3][4][1] = state__[12][3][4][1];
  cipher__[3][4][2] = state__[12][3][4][2];
  cipher__[3][4][3] = state__[12][3][4][3];
  cipher__[3][5][0] = state__[12][3][5][0];
  cipher__[3][5][1] = state__[12][3][5][1];
  cipher__[3][5][2] = state__[12][3][5][2];
  cipher__[3][5][3] = state__[12][3][5][3];
  cipher__[3][6][0] = state__[12][3][6][0];
  cipher__[3][6][1] = state__[12][3][6][1];
  cipher__[3][6][2] = state__[12][3][6][2];
  cipher__[3][6][3] = state__[12][3][6][3];
  cipher__[3][7][0] = state__[12][3][7][0];
  cipher__[3][7][1] = state__[12][3][7][1];
  cipher__[3][7][2] = state__[12][3][7][2];
  cipher__[3][7][3] = state__[12][3][7][3];
  cipher__[4][0][0] = state__[12][4][0][0];
  cipher__[4][0][1] = state__[12][4][0][1];
  cipher__[4][0][2] = state__[12][4][0][2];
  cipher__[4][0][3] = state__[12][4][0][3];
  cipher__[4][1][0] = state__[12][4][1][0];
  cipher__[4][1][1] = state__[12][4][1][1];
  cipher__[4][1][2] = state__[12][4][1][2];
  cipher__[4][1][3] = state__[12][4][1][3];
  cipher__[4][2][0] = state__[12][4][2][0];
  cipher__[4][2][1] = state__[12][4][2][1];
  cipher__[4][2][2] = state__[12][4][2][2];
  cipher__[4][2][3] = state__[12][4][2][3];
  cipher__[4][3][0] = state__[12][4][3][0];
  cipher__[4][3][1] = state__[12][4][3][1];
  cipher__[4][3][2] = state__[12][4][3][2];
  cipher__[4][3][3] = state__[12][4][3][3];
  cipher__[4][4][0] = state__[12][4][4][0];
  cipher__[4][4][1] = state__[12][4][4][1];
  cipher__[4][4][2] = state__[12][4][4][2];
  cipher__[4][4][3] = state__[12][4][4][3];
  cipher__[4][5][0] = state__[12][4][5][0];
  cipher__[4][5][1] = state__[12][4][5][1];
  cipher__[4][5][2] = state__[12][4][5][2];
  cipher__[4][5][3] = state__[12][4][5][3];
  cipher__[4][6][0] = state__[12][4][6][0];
  cipher__[4][6][1] = state__[12][4][6][1];
  cipher__[4][6][2] = state__[12][4][6][2];
  cipher__[4][6][3] = state__[12][4][6][3];
  cipher__[4][7][0] = state__[12][4][7][0];
  cipher__[4][7][1] = state__[12][4][7][1];
  cipher__[4][7][2] = state__[12][4][7][2];
  cipher__[4][7][3] = state__[12][4][7][3];
  cipher__[5][0][0] = state__[12][5][0][0];
  cipher__[5][0][1] = state__[12][5][0][1];
  cipher__[5][0][2] = state__[12][5][0][2];
  cipher__[5][0][3] = state__[12][5][0][3];
  cipher__[5][1][0] = state__[12][5][1][0];
  cipher__[5][1][1] = state__[12][5][1][1];
  cipher__[5][1][2] = state__[12][5][1][2];
  cipher__[5][1][3] = state__[12][5][1][3];
  cipher__[5][2][0] = state__[12][5][2][0];
  cipher__[5][2][1] = state__[12][5][2][1];
  cipher__[5][2][2] = state__[12][5][2][2];
  cipher__[5][2][3] = state__[12][5][2][3];
  cipher__[5][3][0] = state__[12][5][3][0];
  cipher__[5][3][1] = state__[12][5][3][1];
  cipher__[5][3][2] = state__[12][5][3][2];
  cipher__[5][3][3] = state__[12][5][3][3];
  cipher__[5][4][0] = state__[12][5][4][0];
  cipher__[5][4][1] = state__[12][5][4][1];
  cipher__[5][4][2] = state__[12][5][4][2];
  cipher__[5][4][3] = state__[12][5][4][3];
  cipher__[5][5][0] = state__[12][5][5][0];
  cipher__[5][5][1] = state__[12][5][5][1];
  cipher__[5][5][2] = state__[12][5][5][2];
  cipher__[5][5][3] = state__[12][5][5][3];
  cipher__[5][6][0] = state__[12][5][6][0];
  cipher__[5][6][1] = state__[12][5][6][1];
  cipher__[5][6][2] = state__[12][5][6][2];
  cipher__[5][6][3] = state__[12][5][6][3];
  cipher__[5][7][0] = state__[12][5][7][0];
  cipher__[5][7][1] = state__[12][5][7][1];
  cipher__[5][7][2] = state__[12][5][7][2];
  cipher__[5][7][3] = state__[12][5][7][3];
  cipher__[6][0][0] = state__[12][6][0][0];
  cipher__[6][0][1] = state__[12][6][0][1];
  cipher__[6][0][2] = state__[12][6][0][2];
  cipher__[6][0][3] = state__[12][6][0][3];
  cipher__[6][1][0] = state__[12][6][1][0];
  cipher__[6][1][1] = state__[12][6][1][1];
  cipher__[6][1][2] = state__[12][6][1][2];
  cipher__[6][1][3] = state__[12][6][1][3];
  cipher__[6][2][0] = state__[12][6][2][0];
  cipher__[6][2][1] = state__[12][6][2][1];
  cipher__[6][2][2] = state__[12][6][2][2];
  cipher__[6][2][3] = state__[12][6][2][3];
  cipher__[6][3][0] = state__[12][6][3][0];
  cipher__[6][3][1] = state__[12][6][3][1];
  cipher__[6][3][2] = state__[12][6][3][2];
  cipher__[6][3][3] = state__[12][6][3][3];
  cipher__[6][4][0] = state__[12][6][4][0];
  cipher__[6][4][1] = state__[12][6][4][1];
  cipher__[6][4][2] = state__[12][6][4][2];
  cipher__[6][4][3] = state__[12][6][4][3];
  cipher__[6][5][0] = state__[12][6][5][0];
  cipher__[6][5][1] = state__[12][6][5][1];
  cipher__[6][5][2] = state__[12][6][5][2];
  cipher__[6][5][3] = state__[12][6][5][3];
  cipher__[6][6][0] = state__[12][6][6][0];
  cipher__[6][6][1] = state__[12][6][6][1];
  cipher__[6][6][2] = state__[12][6][6][2];
  cipher__[6][6][3] = state__[12][6][6][3];
  cipher__[6][7][0] = state__[12][6][7][0];
  cipher__[6][7][1] = state__[12][6][7][1];
  cipher__[6][7][2] = state__[12][6][7][2];
  cipher__[6][7][3] = state__[12][6][7][3];
  cipher__[7][0][0] = state__[12][7][0][0];
  cipher__[7][0][1] = state__[12][7][0][1];
  cipher__[7][0][2] = state__[12][7][0][2];
  cipher__[7][0][3] = state__[12][7][0][3];
  cipher__[7][1][0] = state__[12][7][1][0];
  cipher__[7][1][1] = state__[12][7][1][1];
  cipher__[7][1][2] = state__[12][7][1][2];
  cipher__[7][1][3] = state__[12][7][1][3];
  cipher__[7][2][0] = state__[12][7][2][0];
  cipher__[7][2][1] = state__[12][7][2][1];
  cipher__[7][2][2] = state__[12][7][2][2];
  cipher__[7][2][3] = state__[12][7][2][3];
  cipher__[7][3][0] = state__[12][7][3][0];
  cipher__[7][3][1] = state__[12][7][3][1];
  cipher__[7][3][2] = state__[12][7][3][2];
  cipher__[7][3][3] = state__[12][7][3][3];
  cipher__[7][4][0] = state__[12][7][4][0];
  cipher__[7][4][1] = state__[12][7][4][1];
  cipher__[7][4][2] = state__[12][7][4][2];
  cipher__[7][4][3] = state__[12][7][4][3];
  cipher__[7][5][0] = state__[12][7][5][0];
  cipher__[7][5][1] = state__[12][7][5][1];
  cipher__[7][5][2] = state__[12][7][5][2];
  cipher__[7][5][3] = state__[12][7][5][3];
  cipher__[7][6][0] = state__[12][7][6][0];
  cipher__[7][6][1] = state__[12][7][6][1];
  cipher__[7][6][2] = state__[12][7][6][2];
  cipher__[7][6][3] = state__[12][7][6][3];
  cipher__[7][7][0] = state__[12][7][7][0];
  cipher__[7][7][1] = state__[12][7][7][1];
  cipher__[7][7][2] = state__[12][7][7][2];
  cipher__[7][7][3] = state__[12][7][7][3];

}


/* **************************************************************** */
/*                            Usuba source                          */
/*                                                                  */
/*

 _no_inline table Sbox(x :  b4 :: base)
  returns y :  b4 :: base
{
  12, 5, 6, 11, 9, 0, 10, 13, 3, 14, 15, 8, 4, 7, 1, 2
}


 node SubCells(x :  b4[8][8] :: base)
  returns y :  b4[8][8] :: base
vars

let
  forall i in [0,7] {
    forall j in [0,7] {
      (y[i][j]) = Sbox(x[i][j])
    }
  }
tel

 node ShiftRows(x :  b4[8][8] :: base)
  returns y :  b4[8][8] :: base
vars

let
  forall i in [0,7] {
    forall j in [0,7] {
      (y[i][j]) = x[i][((j + i) % 8)]
    }
  }
tel

 node AddConstant(x :  b4[8][8] :: base,rc :  b4 :: base)
  returns y :  b4[8][8] :: base
vars
  IC :  b4[8] :: base
let
  (IC) = (0,1,3,7,15,14,12,8);
  forall i in [0,7] {
    (y[i][0]) = ((x[i][0] ^ rc) ^ IC[i]);
    (y[i][1 .. 7]) = x[i][1 .. 7]
  }
tel

 node xtimes(e :  b4 :: base)
  returns e' :  b4 :: base
vars
  t :  b4 :: base,
  c :  b4 :: base
let
  (t) = (e << 1);
  (c) = (e >> 3);
  (e') = (((t & 15) ^ c) ^ (c << 1))
tel

 node step(x :  b4[8] :: base)
  returns x' :  b4[8] :: base
vars
  acc :  b4 :: base
let
  (acc) = 0;
  (acc) := ((acc ^ x[3]) ^ x[5]);
  (acc) := xtimes(acc);
  (acc) := (((acc ^ x[1]) ^ x[6]) ^ x[7]);
  (acc) := xtimes(acc);
  (acc) := (((((acc ^ x[0]) ^ x[2]) ^ x[3]) ^ x[4]) ^ x[7]);
  (acc) := xtimes(acc);
  (acc) := ((acc ^ x[3]) ^ x[6]);
  (x') = (x[1 .. 7],acc)
tel

 node MixColumnRow(X :  b4[8] :: base)
  returns Y :  b4[8] :: base
vars
  x :  b4[9][8] :: base,
  y :  b4[9] :: base
let
  forall i in [0,7] {
    (x[0][i]) = (X[i] & 15)
  };
  forall i in [0,7] {
    (x[(i + 1)]) = step(x[i])
  };
  (Y) = x[8]
tel

 node MixColumnSerial(X :  b4[8][8] :: base)
  returns Y :  b4[8][8] :: base
vars

let
  forall i in [0,7] {
    (Y[0 .. 7][i]) = MixColumnRow(X[0 .. 7][i])
  }
tel

 node Photon(plain :  b4[8][8] :: base)
  returns cipher :  b4[8][8] :: base
vars
  RC :  b4[12] :: base,
  state :  b4[13][8][8] :: base
let
  (RC) = (1,3,7,14,13,11,6,12,9,2,5,10);
  (state[0]) = plain;
  forall i in [0,11] {
    (state[(i + 1)]) = MixColumnSerial(ShiftRows(SubCells(AddConstant(state[i],RC[i]))))
  };
  (cipher) = state[12]
tel

*/
 