/*
 * This file is included from the code generated by bsc, and from
 * orth.h. It is to be considered as public domain, so that it may be
 * used in just about any program without any legal restriction
 */

#ifndef BSC__H__
#define BSC__H__

/*
 * The bsc_u type is supposed to be the longest native integer type
 * of the processor
 */
typedef unsigned long bsc_u;

#define LOG_BSC_U_SIZE	6
#define BSC_U_SIZE	(1UL << LOG_BSC_U_SIZE)

/*
 * This should define a "full -1" bsc_u word. This is NOT ansi. It might
 * have to be modified, depending on the target architecture
 */
#define ALL_ONE ((bsc_u)(-1L))

#endif /* BSC__H__ */
