    rm -rf aes128ctr/cryptopp
    rm -rf chacha20/krovetz
    rm -rf chacha20/moon/avx2
    rm -rf chacha20/moon/sse2
    rm -rf chacha20/usuba-avx
    rm -rf serpent128ctr/usuba-avx
    rm -rf serpent128ctr/usuba-avx-fast
    rm -rf serpent128ctr/usuba-avx
    rm -rf serpent128ctr/usuba-sse*
    rm -rf serpent128ctr/usuba-std*
