/* This code was generated by Usuba.
   See https://github.com/DadaIsCrazy/usuba. */


/* Do NOT change the order of those define/include */
#define NO_RUNTIME
#ifndef BITS_PER_REG
#define BITS_PER_REG 32
#endif
/* including the architecture specific .h */
#include "STD.h"

#undef L_ROTATE
#define L_ROTATE(x,n,c) (x << 1) | ((x >> 2)&1)


/* auxiliary functions */
void _andTI (/*inputs*/ DATATYPE a,DATATYPE b,DATATYPE r, /*outputs*/ DATATYPE* x) {
  
  // Variables declaration
  DATATYPE _tmp1_;
  DATATYPE _tmp2_;
  DATATYPE _tmp3_;
  DATATYPE c1;
  DATATYPE c2;
  DATATYPE c3;
  DATATYPE d1;
  DATATYPE d2;
  DATATYPE d3;
  DATATYPE d4;


  // Instructions (body)
  c1 = AND(a,b);
  _tmp1_ = L_ROTATE(b,1,32);
  c2 = AND(a,_tmp1_);
  _tmp2_ = L_ROTATE(a,1,32);
  c3 = AND(_tmp2_,b);
  d1 = XOR(c1,r);
  d2 = XOR(d1,c2);
  d3 = XOR(d2,c3);
  _tmp3_ = L_ROTATE(r,1,32);
  d4 = XOR(d3,_tmp3_);
  *x = d4;

}

void _notTI (/*inputs*/ DATATYPE a, /*outputs*/ DATATYPE* a__) {
  
  // Variables declaration


  // Instructions (body)
  *a__ = NOT(a);

}

void _orTI (/*inputs*/ DATATYPE a,DATATYPE b,DATATYPE r, /*outputs*/ DATATYPE* x) {
  
  // Variables declaration
  DATATYPE _tmp4_;
  DATATYPE _tmp5_;


  // Instructions (body)
  _notTI(a,&_tmp4_);
  _notTI(b,&_tmp5_);
  _andTI(_tmp4_,_tmp5_,r,&_tmp4_);
  _notTI(_tmp4_,&*x);

}

/* main function */
void adder__ (/*inputs*/ DATATYPE a__,DATATYPE _fd_a__,DATATYPE b__,DATATYPE _fd_b__, /*outputs*/ DATATYPE *s__,DATATYPE *_fd_s__,DATATYPE *c__,DATATYPE *_fd_c__) {
  
  // Variables declaration
  DATATYPE _tmp7_;
  DATATYPE _tmp8_;
  DATATYPE _tmp9_;


  // Instructions (body)
  *s__ = XOR(a__,b__);
  _tmp7_ = XOR(_fd_a__,_fd_b__);
  _notTI(_tmp7_,&*_fd_s__);
  _tmp8_ = rand();
  _andTI(a__,b__,_tmp8_,&*c__);
  //_tmp9_ = rand();
  _tmp9_ = _tmp8_; // Manually modified
  _orTI(_fd_a__,_fd_b__,_tmp9_,&*_fd_c__);

}
 
